### ISSUE TITLE
Python 2.7.13

### ISSUE THREAD

**Issue by fdellutri** [Cebeerre/VerisureAPIClient#11]
I receive the following error:

Traceback (most recent call last):
  File "VerisureToMQTT.py", line 2, in <module>
    from pysecuritas.api.alarm import Alarm
  File "/home/openhabian/.local/lib/python2.7/site-packages/pysecuritas/api/alarm.py", line 11
    def get_available_commands() -> Dict:
                                 ^
SyntaxError: invalid syntax

**Comment by nragon** [comment]
Should be fixed now.

**Comment by fdellutri** [comment]
> Should be fixed now.

Sure, thanks!
